const carsData = [
  {
    id: 1,
    name: 'Dragon, frilled',
    type: 'Toyota',
    model: 'Prius Plug-in Hybrid',
    payment: 'mastercard',
  },
  {
    id: 2,
    name: 'Boa, malagasy ground',
    type: 'Mazda',
    model: '929',
    payment: 'bankcard',
  },
  {
    id: 3,
    name: 'Common palm civet',
    type: 'GMC',
    model: 'EV1',
    payment: 'visa',
  },
  {
    id: 4,
    name: 'Weaver, white-browed sparrow',
    type: 'Ferrari',
    model: '599 GTB Fiorano',
    payment: 'visa',
  },
  {
    id: 5,
    name: 'Wild water buffalo',
    type: 'BMW',
    model: 'Z3',
    payment: 'bankcard',
  },
  {
    id: 6,
    name: 'Common boubou shrike',
    type: 'Mitsubishi',
    model: 'Tredia',
    payment: 'visa',
  },
  {
    id: 7,
    name: 'Argalis',
    type: 'Dodge',
    model: 'Dakota',
    payment: 'visa',
  },
  {
    id: 8,
    name: 'Boa, mexican',
    type: 'Ford',
    model: 'Ranger',
    payment: 'bankcard',
  },
  {
    id: 9,
    name: 'American marten',
    type: 'Toyota',
    model: 'Truck Xtracab SR5',
    payment: 'mastercard',
  },
  {
    id: 10,
    name: 'Hippopotamus',
    type: 'Hummer',
    model: 'H1',
    payment: 'bankcard',
  },
  {
    id: 11,
    name: 'Long-billed cockatoo',
    type: 'Oldsmobile',
    model: 'Cutlass',
    payment: 'bankcard',
  },
  {
    id: 12,
    name: 'Gemsbok',
    type: 'Jeep',
    model: 'Grand Cherokee',
    payment: 'bankcard',
  },
  {
    id: 13,
    name: 'Gull, dusky',
    type: 'Land Rover',
    model: 'Freelander',
    payment: 'bankcard',
  },
  {
    id: 14,
    name: 'Baboon, savanna',
    type: 'Ford',
    model: 'Th!nk',
    payment: 'visa',
  },
  {
    id: 15,
    name: 'Bontebok',
    type: 'GMC',
    model: 'Yukon',
    payment: 'bankcard',
  },
  {
    id: 16,
    name: 'Little grebe',
    type: 'Mazda',
    model: 'Millenia',
    payment: 'visa',
  },
  {
    id: 17,
    name: 'Blackish oystercatcher',
    type: 'Volkswagen',
    model: 'Rabbit',
    payment: 'bankcard',
  },
  {
    id: 18,
    name: 'Shrew, mandras tree',
    type: 'Mitsubishi',
    model: '3000GT',
    payment: 'visa',
  },
  {
    id: 19,
    name: 'Parakeet, rose-ringed',
    type: 'Dodge',
    model: 'Durango',
    payment: 'bankcard',
  },
  {
    id: 20,
    name: 'Javanese cormorant',
    type: 'Suzuki',
    model: 'Grand Vitara',
    payment: 'bankcard',
  },
];

export default carsData;
