const carsData = [
  {
    id: 1,
    name: 'Dragon, frilled',
    type: 'electrical',
    model: 'Toyota',
    payment: 'mastercard',
  },
  {
    id: 2,
    name: 'Boa, malagasy ground',
    type: 'sport',
    model: 'Mazda',
    payment: 'bankcard',
  },
  {
    id: 3,
    name: 'Common palm civet',
    type: 'sport',
    model: 'GMC',
    payment: 'visa',
  },
  {
    id: 4,
    name: 'Weaver, white-browed sparrow',
    type: 'electrical',
    model: 'Ferrari',
    payment: 'visa',
  },
  {
    id: 5,
    name: 'Wild water buffalo',
    type: '2 wheels',
    model: 'BMW',
    payment: 'bankcard',
  },
  {
    id: 6,
    name: 'Common boubou shrike',
    type: 'electrical',
    model: 'Mitsubishi',
    payment: 'visa',
  },
  {
    id: 7,
    name: 'Argalis',
    type: 'electrical',
    model: 'Dodge',
    payment: 'visa',
  },
  {
    id: 8,
    name: 'Boa, mexican',
    type: 'sport',
    model: 'Ford',
    payment: 'bankcard',
  },
  {
    id: 9,
    name: 'American marten',
    type: 'electrical',
    model: 'Toyota',
    payment: 'mastercard',
  },
  {
    id: 10,
    name: 'Hippopotamus',
    type: '2 wheels',
    model: 'Hummer',
    payment: 'bankcard',
  },
  {
    id: 11,
    name: 'Long-billed cockatoo',
    type: 'electrical',
    model: 'Oldsmobile',
    payment: 'bankcard',
  },
  {
    id: 12,
    name: 'Gemsbok',
    type: '2 wheels',
    model: 'Jeep',
    payment: 'bankcard',
  },
  {
    id: 13,
    name: 'Gull, dusky',
    type: 'electrical',
    model: 'Land Rover',
    payment: 'bankcard',
  },
  {
    id: 14,
    name: 'Baboon, savanna',
    type: 'sport',
    model: 'Ford',
    payment: 'visa',
  },
  {
    id: 15,
    name: 'Bontebok',
    type: 'electrical',
    model: 'GMC',
    payment: 'bankcard',
  },
  {
    id: 16,
    name: 'Little grebe',
    type: 'electrical',
    model: 'Mazda',
    payment: 'visa',
  },
  {
    id: 17,
    name: 'Blackish oystercatcher',
    type: '2 wheels',
    model: 'Volkswagen',
    payment: 'bankcard',
  },
  {
    id: 18,
    name: 'Shrew, mandras tree',
    type: 'electrical',
    model: 'Mitsubishi',
    payment: 'visa',
  },
  {
    id: 19,
    name: 'Parakeet, rose-ringed',
    type: 'sport',
    model: 'Dodge',
    payment: 'bankcard',
  },
  {
    id: 20,
    name: 'Javanese cormorant',
    type: '2 wheels',
    model: 'Suzuki',
    payment: 'bankcard',
  },
];

export default carsData;
